In [1]:
#Step1
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


numpy as been installed using pip install


In [6]:
#Step2 
import numpy as np

numpy as been imported as np

In [11]:
lst=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Sum of elements in array: ",np.sum(lst))
print("Mean of elements in array: ",np.mean(lst))
print("Median of elements in array: ",np.median(lst))
print("Standard Deviation of elements in array: ",np.std(lst))

Sum of elements in array:  210
Mean of elements in array:  10.5
Median of elements in array:  10.5
Standard Deviation of elements in array:  5.766281297335398


A 1D array is created using np.array and further sum,mean,median and standard deviation is calculated 
by using the command np.sum,np.mean,np.median,np.std

In [24]:
arr=np.arange(1,17).reshape(4,4)
print("Required Matrix:\n",arr)
transpose_matrix=arr.T
print("Transpose of Matrix:\n", transpose_matrix)

row_sum=arr.sum(axis=1)
column_sum=arr.sum(axis=0)
print("Sum of rows:", row_sum)
print("Sum of columns:", column_sum)

Required Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose of Matrix:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Sum of rows: [10 26 42 58]
Sum of columns: [28 32 36 40]


A matrix is prepared from 1 to 16 using the command np.arrange and s reshape into a 4X4 matrix 
Transpose of the matrix is taken using arr.T 
Sum of the rows of the matrix is taken using arr.sum(axis=1)
Sum of the columns of the matrix is taken using arr.sum(axis=0)

In [26]:
arr1=np.random.randint(1,20,size=(3,3))
arr2=np.random.randint(1,20,size=(3,3))
print("Element wise addition: ", arr1+arr2)
print("Element wise subtraction: ", arr1-arr2)
print("Element wise multiplication: ", arr1*arr2)

print("Dot product of two matrix:\n", arr1.dot(arr2))

Element wise addition:  [[27 26 18]
 [18 14 23]
 [10 23 15]]
Element wise subtraction:  [[  1  12  10]
 [  2 -10   5]
 [ -2   5 -13]]
Element wise multiplication:  [[182 133  56]
 [ 80  24 126]
 [ 24 126  14]]
Dot product of two matrix:
 [[418 452 423]
 [230 220 254]
 [170 205 156]]


In [36]:
arr1=np.random.randint(1,20,size=(3,3))
arr2=np.random.randint(1,20,size=(3,3))
print("1st matrix:\n",arr1)
print("2nd matrix:\n",arr2)
print("Element wise addition:\n ", arr1+arr2)
print("Element wise subtraction:\n ", arr1-arr2)
print("Element wise multiplication:\n ", arr1*arr2)
print("Dot product of two matrix:\n", arr1.dot(arr2))

1st matrix:
 [[13 16  4]
 [ 1 14  9]
 [17 17  3]]
2nd matrix:
 [[ 1 13 17]
 [10  9 16]
 [19 10 14]]
Element wise addition:
  [[14 29 21]
 [11 23 25]
 [36 27 17]]
Element wise subtraction:
  [[ 12   3 -13]
 [ -9   5  -7]
 [ -2   7 -11]]
Element wise multiplication:
  [[ 13 208  68]
 [ 10 126 144]
 [323 170  42]]
Dot product of two matrix:
 [[249 353 533]
 [312 229 367]
 [244 404 603]]


Two new matrix of order 3X3 is made using np.random.radian() and numbers are chosen from 1 to 20
element wise sum of matrix is calculated using arr1+arr2
element wise subtraction of matrix is done using arr1-arr2
element wise multiplication of matrix is done using arr1*arr2
dot production of the matrics is calculated using arr1.dot(arr2)

In [40]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr4=arr3.reshape(3,4)
print("Required matrix:\n",arr4)
arr5=arr4[:2,-2:]
print("sliced matrix:\n",arr5)

Required matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sliced matrix:
 [[3 4]
 [7 8]]


A 1-D array is created using numbers from 1 to 12 and the is transformed into a 3X4 matrix
using .reshape() command and thus the slicing of the matrix for first 2 rows and last 2 columns
is done.